#! /bin/sh

check_allowed() {
    day="$1"
    hour="$2"
    if [ "$day" = "Sat" ] || [ "$day" = "Sun" ]; then # allow on the weekends
        echo "Allowed"
    else                           # weekdays
        if [ "$hour" -lt 9 ]; then # allow before 9am
            echo "Allowed"
        elif [ "$hour" = 12 ]; then # allow between 12pm and 1pm
            echo "Allowed"
        elif [ "$hour" -ge 23 ]; then # allow after 11pm
            echo "Allowed"
        else
            echo "Not allowed"
        fi
    fi
}

if [ -n "$GIT_COMMITTER_DATE" ]; then
    exit 0
fi

if command -v gdate >/dev/null 2>&1; then
    DATE="gdate"
elif command -v date >/dev/null 2>&1; then
    if date --version 2>&1 | grep -q "GNU coreutils"; then
        DATE="date"
    else
        echo "Error: 'date' command found but it isn't GNU date."
        exit 1
    fi
else
    echo "Error: No suitable date command found (gdate or GNU date)."
    exit 1
fi

allowed_now=false
day=$($DATE -d "+${offset} min" +"%a")
hour=$($DATE -d "+${offset} min" +"%H")
if [ "$(check_allowed "$day" "$hour")" = "Allowed" ]; then
    allowed_now=true
fi

ts_latest=$(git log --pretty=format:%ci | sort -n | tail -1)

if [ "$allowed_now" = true ]; then
    echo "allowed to commit now."
    if [ "$($DATE -d "${ts_latest}" +%s)" -gt "$($DATE +%s)" ]; then
        echo "but there are commits in the future."
    else
        echo "and there are no commits in the future."
        exit 0
    fi
fi

commit_time=""
fuzz="$(od -An -N2 -t u2 /dev/urandom | tr -dc '0-9')"
fuzz=$((fuzz % 10))
offset=$fuzz

echo "latest commit time: [${ts_latest}]"
while true; do
    day=$($DATE -d "${ts_latest} +${offset} min" +"%a")
    hour=$($DATE -d "${ts_latest} +${offset} min" +"%H")
    if [ "$(check_allowed "$day" "$hour")" != "Allowed" ]; then
        offset=$((offset + fuzz))
        continue
    fi
    commit_time=$($DATE -d "${ts_latest} +${offset} min" +"%Y-%m-%d %H:%M:%S")
    break
done
if [ "$($DATE -d "$commit_time" +%s)" -gt "$($DATE +%s)" ]; then
    echo "fake commit time: [${commit_time}]"
else
    echo "real commit time: [${commit_time}]"
    exit 0
fi

GIT_AUTHOR_DATE="$($DATE --date="${commit_time}" --iso-8601=seconds)"
GIT_COMMITTER_DATE="$GIT_AUTHOR_DATE"
export GIT_AUTHOR_DATE
export GIT_COMMITTER_DATE

git commit --amend --date "$GIT_AUTHOR_DATE" --no-edit
